name: Release New Version

on:
  pull_request:
    types:
      - closed
      
permissions:
  contents: write
  packages: write


jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: develop
        
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          # git config --global url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/ # Use this line in private repo

      - name: Copy settings.xml
        run: cp ./.github/Maven/settings.xml $HOME/.m2/settings.xml

      - name: Prepare Version
        run: mvn versions:set -DremoveSnapshot

      - name: Setup Graphviz for UML in Javadocs
        uses: ts-graphviz/setup-graphviz@v2

      - name: Generate Javadocs
        run: mvn javadoc:javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}

      - name: Deploy Javadocs to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./target/site/apidocs

      - name: Prepare Version
        run: mvn versions:revert
        
      - name: Prepare Maven Release
        run: |
          mvn release:clean release:prepare -B
        env:
          GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}

      - name: Perform Maven Release
        run: |
          mvn release:perform -B
        env:
          GITHUB_TOKEN: ${{ secrets.JN_TOKEN }}

      - name: Read Current Maven Version
        id: mvn_version
        run: echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
        
      - name: Create new Github Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*-with-dependencies.jar
          tag_name: ${{ steps.mvn_version.outputs.tag }}
          body: |
            Release ${{ steps.mvn_release.output.tag }}
